import React from "react";
import { ArrowLeft, Shield, Lock, Eye, Database, Trash2, Cpu } from "lucide-react";
import logoSrc from "./assets/logo.png";

interface PrivacyPageProps {
  onBack: () => void;
  onNavigateTerms?: () => void;
}

export const PrivacyPage: React.FC<PrivacyPageProps> = ({ onBack, onNavigateTerms }) => {
  return (
    <div className="legal-page-wrap">
      <header className="legal-header">
        <div className="legal-header-inner">
          <button onClick={onBack} className="legal-back-btn" aria-label="Go back">
            <ArrowLeft size={16} /> Back to Studio
          </button>
          <div className="legal-brand">
            <img src={logoSrc} alt="Faceless Art Studio Logo" className="legal-logo" />
            <span>Faceless Art Studio</span>
          </div>
        </div>
      </header>

      <main className="legal-container">
        <article className="legal-card">
          <div className="legal-badge">
            <Shield size={14} /> Privacy &amp; Data Protection Policy
          </div>
          <h1>Privacy Policy</h1>
          <p className="legal-subtitle">
            Effective Date: September 2026 &bull; Last updated: September 2026
          </p>

          <section className="legal-section">
            <h2>1. Overview &amp; Commitment</h2>
            <p>
              Faceless Art Studio (&ldquo;[Company / Entity Name: To be specified]&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) is committed to protecting your privacy. This policy explains what data we collect, how we process it, where it is stored, and your rights concerning your personal and creative data.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Data We Collect &amp; Data Minimization</h2>
            <p>
              We practice strict data minimization. We only collect information strictly necessary to provide the video generation service:
            </p>
            <ul>
              <li><strong>Account Information:</strong> Email address, user identification numbers generated by Supabase, and optional display name/avatar color.</li>
              <li><strong>Creative Inputs:</strong> Scripts, topics, and settings (voice selection, aspect ratios, caption presets) you submit for video creation.</li>
              <li><strong>Uploaded Media:</strong> Video, audio, or image files uploaded to serve as background footage.</li>
              <li><strong>Technical Metadata:</strong> Job statuses, timestamps, generated video durations, and error logs required for service stability.</li>
            </ul>
            <p>
              We <strong>do not</strong> collect or log your passwords (passwords are securely hashed and managed exclusively by Supabase Auth), payment card details, or unnecessary personal telemetry.
            </p>
          </section>

          <section className="legal-section">
            <h2>3. Third-Party Services &amp; Architecture Audit</h2>
            <p>
              The application uses the following components to execute the creative pipeline:
            </p>
            <div className="legal-services-grid">
              <div className="legal-service-box">
                <Database size={20} className="legal-box-icon" />
                <h3>Supabase Auth &amp; Database</h3>
                <p>
                  Handles identity authentication, user session verification, and stores account-scoped project records with strict Row Level Security (RLS).
                </p>
              </div>
              <div className="legal-service-box">
                <Cpu size={20} className="legal-box-icon" />
                <h3>AI Voice Synthesis (Edge TTS)</h3>
                <p>
                  Generates natural voiceovers from your provided script text. Transmits only the script text and voice preference to the voice generation engine.
                </p>
              </div>
              <div className="legal-service-box">
                <Lock size={20} className="legal-box-icon" />
                <h3>OpenAI Whisper (Local Transcription)</h3>
                <p>
                  Generates precise word-level subtitle timing files (SRT / ASS). Transcribes synthesized speech locally or on the studio backend.
                </p>
              </div>
              <div className="legal-service-box">
                <Eye size={20} className="legal-box-icon" />
                <h3>FFmpeg (Video Compositing)</h3>
                <p>
                  Combines the background video, voiceover track, and animated captions into the final MP4 output. Operates entirely inside the studio pipeline.
                </p>
              </div>
            </div>
          </section>

          <section className="legal-section">
            <h2>4. Account Isolation &amp; Media Security</h2>
            <p>
              All projects, generated media files, and notifications are strictly account-scoped. Supabase Row Level Security restricts database access to the authenticated user ID (<code>auth.uid() = user_id</code>). All backend downloads and media preview endpoints require verified Bearer tokens and enforce identity checks to prevent cross-account access.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. Cookies &amp; Browser Storage</h2>
            <p>
              Faceless Art Studio uses essential browser storage (such as <code>localStorage</code>) to maintain core application functionality. Specifically:
            </p>
            <ul>
              <li><strong>Authentication Sessions:</strong> Securely maintaining your Supabase session tokens between visits.</li>
              <li><strong>Studio Preferences:</strong> Remembering your theme mode, auto-save toggle, and default landing page preference.</li>
              <li><strong>Editor State:</strong> Storing in-progress draft scripts so your work is not lost if the browser is reloaded.</li>
              <li><strong>Cookie Consent:</strong> Remembering your consent response (under the key <code>faceless-art-studio-cookie-consent</code>) so you are not repeatedly prompted.</li>
            </ul>
            <p>
              We <strong>do not</strong> use third-party advertising, marketing, or behavioral profiling cookies. Declining optional cookies through our consent banner records your preference and does not disable the essential technical storage required to operate the studio.
            </p>
          </section>

          <section className="legal-section">
            <h2>6. Your Rights &amp; Data Deletion</h2>
            <p>
              You maintain complete ownership of your creative scripts and generated video outputs. You have the right to:
            </p>
            <ul>
              <li>Export or download any project, video, audio, or subtitle file at any time.</li>
              <li>Delete individual projects and notifications through the studio dashboard.</li>
              <li><strong>Delete Your Account and All Associated Data:</strong> You may trigger account deletion directly from <em>Workspace Settings &gt; Account Management</em>. Deleting your account immediately removes your database records (profiles, projects, notifications) and deletes generated media files from the studio filesystem.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>7. Contact &amp; Questions</h2>
            <p>
              If you have any questions or data requests regarding this Privacy Policy, please contact our team at:
              <br />
              <strong>Privacy Inquiries:</strong> <code>[privacy@yourdomain.com / Support contact to be specified]</code>
            </p>
            {onNavigateTerms && (
              <p style={{ marginTop: 16 }}>
                Please also review our{" "}
                <button
                  type="button"
                  onClick={onNavigateTerms}
                  style={{
                    background: "none",
                    border: "none",
                    color: "var(--blue, #1e8cfa)",
                    cursor: "pointer",
                    textDecoration: "underline",
                    padding: 0,
                    font: "inherit",
                  }}
                >
                  Terms of Service
                </button>.
              </p>
            )}
          </section>
        </article>
      </main>
    </div>
  );
};
